import { NextResponse } from "next/server";

// Example API route for fetching items
export async function GET() {
  try {
    // This is where you would fetch from your database
    const items = [
      { id: 1, name: "Item 1", description: "Description 1" },
      { id: 2, name: "Item 2", description: "Description 2" },
      { id: 3, name: "Item 3", description: "Description 3" },
    ];

    return NextResponse.json({ items });
  } catch (error) {
    console.error("Error fetching items:", error);
    return NextResponse.json(
      { error: "Failed to fetch items" },
      { status: 500 }
    );
  }
}

// Example API route for creating items
export async function POST(request: Request) {
  try {
    const body = await request.json();
    
    // This is where you would insert into your database
    const newItem = {
      id: Date.now(), // In a real app, this would be generated by the database
      ...body,
      created_at: new Date().toISOString(),
    };

    return NextResponse.json({ item: newItem }, { status: 201 });
  } catch (error) {
    console.error("Error creating item:", error);
    return NextResponse.json(
      { error: "Failed to create item" },
      { status: 500 }
    );
  }
}